# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PSDanTangSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PSDanTangSwift

  target 'PSDanTangSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SnapKit', '~> 3.1.2'
pod 'Kingfisher', '~>3.3.4'
pod 'Alamofire', '~> 4.3.0'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'ObjectMapper'
pod 'SDCycleScrollView'

  target 'PSDanTangSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
